version: '3.4'

services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - 5432:5432

  library.api:
    container_name: api
    image: library
    build:
      context: .
      dockerfile: Library.Api/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db